# Render.com deployment configuration for AI Quiz Microservice

services:
  # Web Service (FastAPI Application)
  - type: web
    name: ai-quiz-microservice
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -e .
    startCommand: python start.py
    healthCheckPath: /healthz
    envVars:
      - key: ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-quiz-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-quiz-redis
          property: connectionString
      # Add your own in Render dashboard as needed:
      # - OPENAI_API_KEY
      # - GEMINI_API_KEY
      # - NOTIFICATION_ENABLED=true
      # - SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, SMTP_USE_TLS, NOTIFICATION_FROM_EMAIL

  # Redis Service (for caching)
  - type: redis
    name: ai-quiz-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    # Required: explicitly specify allow list (empty = internal only)
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: ai-quiz-postgres
    plan: free
    databaseName: quiz_db
    user: quiz_user
    # Required: explicitly specify allow list (empty = internal only)
    ipAllowList: []

# Note: Free tier limitations on Render:
# - Web service: 750 hours/month, sleeps after 15 min of inactivity
# - PostgreSQL: 1GB storage, 100 connections
# - Redis: 25MB storage
# - Custom domains require paid plan
